### ISSUE TITLE
source-css init fails to add data to source.config.json

### ISSUE THREAD

**Issue by dmagunov** [namad/sds-bootstrapper#3]
Hi, thanks for the wonderful library. I'm trying to set it up locally, but when I run `pnpm exec source-css init`, it creates an empty `source.config.json` file. Here is the screenshot:

<img width="1473" alt="Screenshot 2024-10-24 at 10 26 37" src="https://github.com/user-attachments/assets/5ca26e9c-b5f5-4017-8813-329da9e4bb15">

**Comment by namad** [comment]
Hi, thanks for letting me know! 

I confirm the issie and I just released a new version `source-foundation-cli@1.0.7`, this one should initialize properly.

**Comment by namad** [comment]
Please let me know if you have issues, mate

**Comment by namad** [comment]
Despite the fix the tools does not generate CSS files, let me look deeper into the issue, seems like there are some recent code changes that does not go well with CLI

**Comment by namad** [comment]
alright, should be done now, check `source-foundation-cli@1.0.7`, going to be much more reliable

**Comment by dmagunov** [comment]
Thanks, confirmed, it's working now
